#pragma once

typedef struct {
  const char *label;   // shown in MenuLayer picker (sorted A-Z)
  const char *city;    // shown on watchface below the second clock
  int16_t     offset;  // UTC offset in minutes (negative = west of UTC)
} TimezoneEntry;

static const TimezoneEntry TIMEZONES[] = {
  { "Afghanistan",               "Kabul",           270 },
  { "Alaska (Standard)",         "Anchorage",      -540 },
  { "Alaska (Summer/DST)",       "Anchorage",      -480 },
  { "Albania (Standard)",        "Tirana",           60 },
  { "Albania (Summer/DST)",      "Tirana",          120 },
  { "Algeria",                   "Algiers",          60 },
  { "American Samoa",            "Pago Pago",      -660 },
  { "Andorra (Standard)",        "Andorra",          60 },
  { "Andorra (Summer/DST)",      "Andorra",         120 },
  { "Angola",                    "Luanda",           60 },
  { "Argentina",                 "Buenos Aires",   -180 },
  { "Armenia",                   "Yerevan",         240 },
  { "Australia - Adelaide",      "Adelaide",        570 },
  { "Australia - Adelaide (Sum)","Adelaide",        630 },
  { "Australia - Brisbane",      "Brisbane",        600 },
  { "Australia - Darwin",        "Darwin",          570 },
  { "Australia - Lord Howe",     "Lord Howe",       630 },
  { "Australia - Lord Howe (S)", "Lord Howe",       660 },
  { "Australia - Melbourne",     "Melbourne",       600 },
  { "Australia - Melbourne (S)", "Melbourne",       660 },
  { "Australia - Perth",         "Perth",           480 },
  { "Australia - Sydney",        "Sydney",          600 },
  { "Australia - Sydney (Sum)",  "Sydney",          660 },
  { "Austria (Standard)",        "Vienna",           60 },
  { "Austria (Summer/DST)",      "Vienna",          120 },
  { "Azerbaijan",                "Baku",            240 },
  { "Bahamas (Standard)",        "Nassau",         -300 },
  { "Bahamas (Summer/DST)",      "Nassau",         -240 },
  { "Bahrain",                   "Manama",          180 },
  { "Bangladesh",                "Dhaka",           360 },
  { "Belarus",                   "Minsk",           180 },
  { "Belgium (Standard)",        "Brussels",         60 },
  { "Belgium (Summer/DST)",      "Brussels",        120 },
  { "Belize",                    "Belmopan",       -360 },
  { "Bhutan",                    "Thimphu",         360 },
  { "Bolivia",                   "La Paz",         -240 },
  { "Bosnia (Standard)",         "Sarajevo",         60 },
  { "Bosnia (Summer/DST)",       "Sarajevo",        120 },
  { "Botswana",                  "Gaborone",        120 },
  { "Brazil - Brasilia",         "Brasilia",       -180 },
  { "Brazil - Manaus",           "Manaus",         -240 },
  { "Brunei",                    "Bandar Seri",     480 },
  { "Bulgaria (Standard)",       "Sofia",           120 },
  { "Bulgaria (Summer/DST)",     "Sofia",           180 },
  { "Burkina Faso",              "Ouagadougou",       0 },
  { "Myanmar",                   "Yangon",          390 },
  { "Cambodia",                  "Phnom Penh",      420 },
  { "Cameroon",                  "Yaounde",          60 },
  { "Canada - Atlantic (Std)",   "Halifax",        -240 },
  { "Canada - Atlantic (Sum)",   "Halifax",        -180 },
  { "Canada - Central (Std)",    "Winnipeg",       -360 },
  { "Canada - Central (Sum)",    "Winnipeg",       -300 },
  { "Canada - Eastern (Std)",    "Toronto",        -300 },
  { "Canada - Eastern (Sum)",    "Toronto",        -240 },
  { "Canada - Mountain (Std)",   "Calgary",        -420 },
  { "Canada - Mountain (Sum)",   "Calgary",        -360 },
  { "Canada - Nfld (Standard)",  "St. John's",     -210 },
  { "Canada - Nfld (Summer)",    "St. John's",     -150 },
  { "Canada - Pacific (Std)",    "Vancouver",      -480 },
  { "Canada - Pacific (Sum)",    "Vancouver",      -420 },
  { "Cape Verde",                "Praia",           -60 },
  { "Chad",                      "N'Djamena",        60 },
  { "Chile (Standard)",          "Santiago",       -240 },
  { "Chile (Summer/DST)",        "Santiago",       -180 },
  { "China",                     "Beijing",         480 },
  { "Colombia",                  "Bogota",         -300 },
  { "Congo",                     "Brazzaville",      60 },
  { "Costa Rica",                "San Jose",       -360 },
  { "Croatia (Standard)",        "Zagreb",           60 },
  { "Croatia (Summer/DST)",      "Zagreb",          120 },
  { "Cuba (Standard)",           "Havana",         -300 },
  { "Cuba (Summer/DST)",         "Havana",         -240 },
  { "Cyprus (Standard)",         "Nicosia",         120 },
  { "Cyprus (Summer/DST)",       "Nicosia",         180 },
  { "Czech Republic (Std)",      "Prague",           60 },
  { "Czech Republic (Sum)",      "Prague",          120 },
  { "Denmark (Standard)",        "Copenhagen",       60 },
  { "Denmark (Summer/DST)",      "Copenhagen",      120 },
  { "Djibouti",                  "Djibouti",        180 },
  { "Dominican Republic",        "Santo Domingo",  -240 },
  { "Ecuador",                   "Quito",          -300 },
  { "Egypt",                     "Cairo",           120 },
  { "El Salvador",               "San Salvador",   -360 },
  { "Estonia (Standard)",        "Tallinn",         120 },
  { "Estonia (Summer/DST)",      "Tallinn",         180 },
  { "Ethiopia",                  "Addis Ababa",     180 },
  { "Fiji (Standard)",           "Suva",            720 },
  { "Fiji (Summer/DST)",         "Suva",            780 },
  { "Finland (Standard)",        "Helsinki",        120 },
  { "Finland (Summer/DST)",      "Helsinki",        180 },
  { "France (Standard)",         "Paris",            60 },
  { "France (Summer/DST)",       "Paris",           120 },
  { "French Polynesia",          "Papeete",        -600 },
  { "Georgia",                   "Tbilisi",         240 },
  { "Germany (Standard)",        "Berlin",           60 },
  { "Germany (Summer/DST)",      "Berlin",          120 },
  { "Ghana",                     "Accra",             0 },
  { "Greece (Standard)",         "Athens",          120 },
  { "Greece (Summer/DST)",       "Athens",          180 },
  { "Guatemala",                 "Guatemala City",  -360 },
  { "Guyana",                    "Georgetown",     -240 },
  { "Haiti (Standard)",          "Port-au-Prince", -300 },
  { "Haiti (Summer/DST)",        "Port-au-Prince", -240 },
  { "Hawaii",                    "Honolulu",       -600 },
  { "Honduras",                  "Tegucigalpa",    -360 },
  { "Hong Kong",                 "Hong Kong",       480 },
  { "Hungary (Standard)",        "Budapest",         60 },
  { "Hungary (Summer/DST)",      "Budapest",        120 },
  { "Iceland",                   "Reykjavik",         0 },
  { "India",                     "Mumbai",          330 },
  { "Indonesia - Jakarta",       "Jakarta",         420 },
  { "Indonesia - Jayapura",      "Jayapura",        540 },
  { "Indonesia - Makassar",      "Makassar",        480 },
  { "Iran (Standard)",           "Tehran",          210 },
  { "Iran (Summer/DST)",         "Tehran",          270 },
  { "Iraq",                      "Baghdad",         180 },
  { "Ireland (Standard)",        "Dublin",            0 },
  { "Ireland (Summer/DST)",      "Dublin",           60 },
  { "Israel (Standard)",         "Jerusalem",       120 },
  { "Israel (Summer/DST)",       "Jerusalem",       180 },
  { "Italy (Standard)",          "Rome",             60 },
  { "Italy (Summer/DST)",        "Rome",            120 },
  { "Jamaica",                   "Kingston",       -300 },
  { "Japan",                     "Tokyo",           540 },
  { "Jordan (Standard)",         "Amman",           120 },
  { "Jordan (Summer/DST)",       "Amman",           180 },
  { "Kazakhstan - Almaty",       "Almaty",          360 },
  { "Kazakhstan - Aqtau",        "Aqtau",           300 },
  { "Kenya",                     "Nairobi",         180 },
  { "Kiribati - Gilbert",        "Tarawa",          720 },
  { "Kiribati - Line",           "Kiritimati",      840 },
  { "Kuwait",                    "Kuwait City",     180 },
  { "Kyrgyzstan",                "Bishkek",         360 },
  { "Laos",                      "Vientiane",       420 },
  { "Latvia (Standard)",         "Riga",            120 },
  { "Latvia (Summer/DST)",       "Riga",            180 },
  { "Lebanon (Standard)",        "Beirut",          120 },
  { "Lebanon (Summer/DST)",      "Beirut",          180 },
  { "Liberia",                   "Monrovia",          0 },
  { "Libya",                     "Tripoli",         120 },
  { "Lithuania (Standard)",      "Vilnius",         120 },
  { "Lithuania (Summer/DST)",    "Vilnius",         180 },
  { "Luxembourg (Standard)",     "Luxembourg",       60 },
  { "Luxembourg (Summer/DST)",   "Luxembourg",      120 },
  { "Macau",                     "Macau",           480 },
  { "Madagascar",                "Antananarivo",    180 },
  { "Malawi",                    "Lilongwe",        120 },
  { "Malaysia",                  "Kuala Lumpur",    480 },
  { "Maldives",                  "Male",            300 },
  { "Mali",                      "Bamako",            0 },
  { "Malta (Standard)",          "Valletta",         60 },
  { "Malta (Summer/DST)",        "Valletta",        120 },
  { "Marshall Islands",          "Majuro",          720 },
  { "Mauritania",                "Nouakchott",        0 },
  { "Mauritius",                 "Port Louis",      240 },
  { "Mexico - Central (Std)",    "Mexico City",    -360 },
  { "Mexico - Central (Sum)",    "Mexico City",    -300 },
  { "Mexico - Northwest (Std)",  "Tijuana",        -480 },
  { "Mexico - Northwest (Sum)",  "Tijuana",        -420 },
  { "Mexico - Pacific (Std)",    "Mazatlan",       -420 },
  { "Mexico - Pacific (Sum)",    "Mazatlan",       -360 },
  { "Moldova (Standard)",        "Chisinau",        120 },
  { "Moldova (Summer/DST)",      "Chisinau",        180 },
  { "Mongolia",                  "Ulaanbaatar",     480 },
  { "Morocco",                   "Casablanca",       60 },
  { "Mozambique",                "Maputo",          120 },
  { "Namibia",                   "Windhoek",        120 },
  { "Nepal",                     "Kathmandu",       345 },
  { "Netherlands (Standard)",    "Amsterdam",        60 },
  { "Netherlands (Summer/DST)",  "Amsterdam",       120 },
  { "New Caledonia",             "Noumea",          660 },
  { "New Zealand (Standard)",    "Auckland",        720 },
  { "New Zealand (Summer/DST)",  "Auckland",        780 },
  { "Nicaragua",                 "Managua",        -360 },
  { "Nigeria",                   "Lagos",            60 },
  { "North Korea",               "Pyongyang",       540 },
  { "Norway (Standard)",         "Oslo",             60 },
  { "Norway (Summer/DST)",       "Oslo",            120 },
  { "Oman",                      "Muscat",          240 },
  { "Pakistan",                  "Karachi",         300 },
  { "Palestine (Standard)",      "Ramallah",        120 },
  { "Palestine (Summer/DST)",    "Ramallah",        180 },
  { "Panama",                    "Panama City",    -300 },
  { "Papua New Guinea",          "Port Moresby",    600 },
  { "Paraguay (Standard)",       "Asuncion",       -240 },
  { "Paraguay (Summer/DST)",     "Asuncion",       -180 },
  { "Peru",                      "Lima",           -300 },
  { "Philippines",               "Manila",          480 },
  { "Poland (Standard)",         "Warsaw",           60 },
  { "Poland (Summer/DST)",       "Warsaw",          120 },
  { "Portugal (Standard)",       "Lisbon",            0 },
  { "Portugal (Summer/DST)",     "Lisbon",           60 },
  { "Puerto Rico",               "San Juan",       -240 },
  { "Qatar",                     "Doha",            180 },
  { "Romania (Standard)",        "Bucharest",       120 },
  { "Romania (Summer/DST)",      "Bucharest",       180 },
  { "Russia - Irkutsk",          "Irkutsk",         480 },
  { "Russia - Kaliningrad",      "Kaliningrad",     120 },
  { "Russia - Kamchatka",        "Petropavlovsk",   720 },
  { "Russia - Krasnoyarsk",      "Krasnoyarsk",     420 },
  { "Russia - Magadan",          "Magadan",         660 },
  { "Russia - Moscow",           "Moscow",          180 },
  { "Russia - Omsk",             "Omsk",            360 },
  { "Russia - Samara",           "Samara",          240 },
  { "Russia - Vladivostok",      "Vladivostok",     600 },
  { "Russia - Yakutsk",          "Yakutsk",         540 },
  { "Russia - Yekaterinburg",    "Yekaterinburg",   300 },
  { "Rwanda",                    "Kigali",          120 },
  { "Samoa",                     "Apia",            780 },
  { "Saudi Arabia",              "Riyadh",          180 },
  { "Senegal",                   "Dakar",             0 },
  { "Serbia (Standard)",         "Belgrade",         60 },
  { "Serbia (Summer/DST)",       "Belgrade",        120 },
  { "Seychelles",                "Victoria",        240 },
  { "Singapore",                 "Singapore",       480 },
  { "Slovakia (Standard)",       "Bratislava",       60 },
  { "Slovakia (Summer/DST)",     "Bratislava",      120 },
  { "Slovenia (Standard)",       "Ljubljana",        60 },
  { "Slovenia (Summer/DST)",     "Ljubljana",       120 },
  { "Solomon Islands",           "Honiara",         660 },
  { "Somalia",                   "Mogadishu",       180 },
  { "South Africa",              "Johannesburg",    120 },
  { "South Korea",               "Seoul",           540 },
  { "South Sudan",               "Juba",            180 },
  { "Spain (Standard)",          "Madrid",           60 },
  { "Spain (Summer/DST)",        "Madrid",          120 },
  { "Sri Lanka",                 "Colombo",         330 },
  { "Sudan",                     "Khartoum",        180 },
  { "Suriname",                  "Paramaribo",     -180 },
  { "Sweden (Standard)",         "Stockholm",        60 },
  { "Sweden (Summer/DST)",       "Stockholm",       120 },
  { "Switzerland (Standard)",    "Zurich",           60 },
  { "Switzerland (Summer/DST)",  "Zurich",          120 },
  { "Syria (Standard)",          "Damascus",        120 },
  { "Syria (Summer/DST)",        "Damascus",        180 },
  { "Taiwan",                    "Taipei",          480 },
  { "Tajikistan",                "Dushanbe",        300 },
  { "Tanzania",                  "Dar es Salaam",   180 },
  { "Thailand",                  "Bangkok",         420 },
  { "Timor-Leste",               "Dili",            540 },
  { "Tonga",                     "Nuku'alofa",      780 },
  { "Trinidad & Tobago",         "Port of Spain",  -240 },
  { "Tunisia",                   "Tunis",            60 },
  { "Turkey",                    "Istanbul",        180 },
  { "Turkmenistan",              "Ashgabat",        300 },
  { "Uganda",                    "Kampala",         180 },
  { "Ukraine (Standard)",        "Kyiv",            120 },
  { "Ukraine (Summer/DST)",      "Kyiv",            180 },
  { "United Arab Emirates",      "Dubai",           240 },
  { "United Kingdom (Standard)", "London",            0 },
  { "United Kingdom (Summer)",   "London",           60 },
  { "Uruguay",                   "Montevideo",     -180 },
  { "USA - Alaska (Standard)",   "Anchorage",      -540 },
  { "USA - Alaska (Summer/DST)", "Anchorage",      -480 },
  { "USA - Central (Standard)",  "Chicago",        -360 },
  { "USA - Central (Summer/DST)","Chicago",        -300 },
  { "USA - Eastern (Standard)",  "New York",       -300 },
  { "USA - Eastern (Summer/DST)","New York",       -240 },
  { "USA - Hawaii",              "Honolulu",       -600 },
  { "USA - Mountain (Standard)", "Denver",         -420 },
  { "USA - Mountain (Summer)",   "Denver",         -360 },
  { "USA - Pacific (Standard)",  "Los Angeles",    -480 },
  { "USA - Pacific (Summer/DST)","Los Angeles",    -420 },
  { "UTC",                       "UTC",               0 },
  { "Uzbekistan",                "Tashkent",        300 },
  { "Vanuatu",                   "Port Vila",       660 },
  { "Venezuela",                 "Caracas",        -240 },
  { "Vietnam",                   "Ho Chi Minh",     420 },
  { "Yemen",                     "Sanaa",           180 },
  { "Zambia",                    "Lusaka",          120 },
  { "Zimbabwe",                  "Harare",          120 },
};

#define NUM_TIMEZONES ((int)(sizeof(TIMEZONES) / sizeof(TIMEZONES[0])))
